version: '3'
services:
    pagila:
        build: .
        container_name: pagila
        hostname: pagila
        # environment:
        #     POSTGRES_PASSWORD: ${PAGILA_PASSWORD}
        #     POSTGRES_USER: ${PAGILA_USER}
        expose:
            - 5432
        networks:
            - pagila-network

networks:
    pagila-network:
        external: true
